sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- mkdir _build
- pdflatex -interaction=nonstopmode  -output-directory _build tex/main.tex
before_deploy:
  - git config --local user.name "Travis CI"
  - git config --local user.email "travis@travis-ci.org"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: iCVvbQkm00n0QdjLbEaC+7mQy8w9OSRAVIiog1ZCcZ0FPf62ZPvMcCoXKtM/f65reCt/oFjBFVtx61r7J6FO9xkFZqjKQ44fH6UKH5SvBhRJ7nbxxbZkmu9JAr5f+zgKf2FOggDBSDuKN5p0zumVLOaqUEe1BBAp1a/ZFuqSUBUqErFmxLzJ6z8nQkBe2Jvzn/bGf7T2U78tS4l95fojmOAw+DRQnlpIuEcZcpqPHHmgYHrCFdYCf0ahi52UBQwqG/z6e4vfQ4/XDP5fVsrw4JMGYnoqwqKS/efie7gc/bk4sGfZWCdIZ49n8w9S5HEJGiOBK6+aSB9MM7yNMqTRjrn4MEbyNvpK2HExYqk+6n0zOnH2lkWMCDqF/4uhDp0XzyN8rHiYHR6p1tskm7+PR79ArLYQF14uAFhXGgVL3EdaPRk1dqe4ygXv8oBpQqcOxZ7Hf7cAYFdkUq4pi8uZHGjquSv/u6GC9rCryNSDrhYSlBCZRFC31scf7aKxThZHq0QLNe5uXsyAAVNsXdhtU0MGGvv6IT17t9L4rCo5NX2XAWaYI2+ReFCRDhYr1ahl6ii/pNk6mFgK3ldMDtX7b/vTWmKzEpHC0BmJ/vOe++PsE7iRSA5hG5WilxoNV9jxISHHzxTlFlHA1LshMZvPIqfS6WkciOFRixr8818rzK8=
  file: _build/*
  skip_cleanup: true
  on:
    repo: jc0b/Logic-and-Modelling
    tags: false
